# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np



In [4]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()



   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables


In [5]:
# frequency table for prestige and whether or not someone was admitted
pd.crosstab([df.prestige, df.admit], columns="count")


col_0           count
prestige admit       
1.0      0         28
         1         33
2.0      0         95
         1         53
3.0      0         93
         1         28
4.0      0         55
         1         12

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [6]:
prestige_dummies = pd.get_dummies(df['prestige'])
print prestige_dummies.head()


   1.0  2.0  3.0  4.0
0  0.0  0.0  1.0  0.0
1  0.0  0.0  1.0  0.0
2  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0
4  0.0  0.0  0.0  1.0


#### 2.2 When modeling our class variables, how many do we need? 



Answer: 3

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [7]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(prestige_dummies.ix[:, 0:3])
print handCalc.head()



   admit    gre   gpa  1.0  2.0  3.0
0      0  380.0  3.61  0.0  0.0  1.0
1      1  660.0  3.67  0.0  0.0  1.0
2      1  800.0  4.00  1.0  0.0  0.0
3      1  640.0  3.19  0.0  0.0  0.0
4      0  520.0  2.93  0.0  0.0  0.0


In [14]:
#crosstab prestige 1 admission 
# frequency table cutting prestige and whether or not someone was admitted

# do *not* do this to rename columns, reassign like columns = ['col1', 'col2']
# handCalc.columns.values[3]='prestige1'
# handCalc.columns.values[4]='prestige2'
# handCalc.columns.values[5]='prestige3'

print handCalc.columns.tolist()

pd.crosstab(handCalc['admit'], handCalc[1.0], rownames=['admit'])



['admit', 'gre', 'gpa', 1.0, 2.0, 3.0]


1.0    0.0  1.0
admit          
0      243   28
1       93   33

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college


In [17]:
pd.crosstab(handCalc['admit'], handCalc[1.0], rownames=['admit']).apply(lambda r: r/len(df), axis=1)



1.0         0.0       1.0
admit                    
0      0.612091  0.070529
1      0.234257  0.083123

#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

#### 3.3 Calculate the odds ratio

#### 3.4 Write this finding in a sentenance: 

Answer: 

I'm not sure how to calculate the odds.


#### 3.5 Print the cross tab for prestige_4

#### 3.6 Calculate the OR 

#### 3.7 Write this finding in a sentence

Answer:

## Part 4. Analysis

In [46]:
# create a clean data frame for the regression
dummy_ranks = prestige_dummies
cols_to_keep = ['admit', 'gre', 'gpa']
data = df[cols_to_keep].join(dummy_ranks.ix[:, 1:])
print data.head()



   admit    gre   gpa  1.0  2.0  3.0  4.0
0      0  380.0  3.61  0.0  0.0  1.0  0.0
1      1  660.0  3.67  0.0  0.0  1.0  0.0
2      1  800.0  4.00  1.0  0.0  0.0  0.0
3      1  640.0  3.19  0.0  0.0  0.0  1.0
4      0  520.0  2.93  0.0  0.0  0.0  1.0


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [47]:
# manually add the intercept
data['intercept'] = 1.0



#### 4.1 Set the covariates to a variable called train_cols



In [48]:
train_cols = data.cov()


In [49]:
train_cols

admit           gre        gpa       1.0       2.0       3.0  \
admit      0.217197      9.772155   0.030852  0.034444  0.015221 -0.026270   
gre        9.772155  13390.606315  16.824761  3.688395  3.274941 -3.967000   
gpa        0.030852     16.824761   0.144558  0.009377 -0.009297  0.012421   
1.0        0.034444      3.688395   0.009377  0.130372 -0.057426 -0.046949   
2.0        0.015221      3.274941  -0.009297 -0.057426  0.234410 -0.113910   
3.0       -0.026270     -3.967000   0.012421 -0.046949 -0.113910  0.212427   
4.0       -0.023395     -2.996336  -0.012501 -0.025997 -0.063074 -0.051567   
intercept  0.000000      0.000000   0.000000  0.000000  0.000000  0.000000   

                4.0  intercept  
admit     -0.023395        0.0  
gre       -2.996336        0.0  
gpa       -0.012501        0.0  
1.0       -0.025997        0.0  
2.0       -0.063074        0.0  
3.0       -0.051567        0.0  
4.0        0.140638        0.0  
intercept  0.000000        0.0

#### 4.2 Fit the model

In [50]:
from sklearn.linear_model import LogisticRegression


In [57]:
lm = LogisticRegression()
lm.fit(data[1.0], data['admit']) ## not sure how to shape/what to use exactly.. 

/Users/sedkin/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: bad input shape (1, 397)

#### 4.3 Print the summary results

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

#### 4.5 Interpret the OR of Prestige_2

Answer: 

#### 4.6 Interpret the OR of GPA

Answer: 

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [52]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out



In [54]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(data['gre'].min(), data['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(data['gpa'].min(), data['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))



[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


#### 5.1 Recreate the dummy variables

In [63]:
# recreate the dummy variables
dummies = pd.get_dummies(combos)
print dummies.head()
# keep only what we need for making predictions



       0         1    2    3
0  220.0  2.260000  1.0  1.0
1  220.0  2.260000  2.0  1.0
2  220.0  2.260000  3.0  1.0
3  220.0  2.260000  4.0  1.0
4  220.0  2.453333  1.0  1.0


#### 5.2 Make predictions on the enumerated dataset

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.